import { Category } from '../models/product.model';

export const CATEGORIES: Category[] = [
  {
    id: 'cat-men',
    name: 'Men',
    slug: 'men',
    parentId: null,
    description: 'Considered essentials for everyday wear.',
    image: 'https://images.unsplash.com/photo-1516257984-b1b4d707412e?w=800',
    status: 'active',
    sortOrder: 1,
    attributeIds: ['attr-color', 'attr-size', 'attr-fabric', 'attr-fit'],
  },
  {
    id: 'cat-women',
    name: 'Women',
    slug: 'women',
    parentId: null,
    description: 'Modern silhouettes, made to last.',
    image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800',
    status: 'active',
    sortOrder: 2,
    attributeIds: ['attr-color', 'attr-size', 'attr-fabric', 'attr-fit'],
  },
  {
    id: 'cat-kids',
    name: 'Kids',
    slug: 'kids',
    parentId: null,
    description: 'Playful, durable, easy to move in.',
    image: 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=800',
    status: 'active',
    sortOrder: 3,
    attributeIds: ['attr-color', 'attr-size'],
  },
  {
    id: 'cat-accessories',
    name: 'Accessories',
    slug: 'accessories',
    parentId: null,
    description: 'The finishing details.',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800',
    status: 'active',
    sortOrder: 4,
    attributeIds: ['attr-color'],
  },
  // Sub-categories referenced by product.subCategoryId and by the mega menu links
  { id: 'cat-mens-tshirts', name: "Men's T-Shirts", slug: 'mens-t-shirts', parentId: 'cat-men', status: 'active', sortOrder: 1, attributeIds: ['attr-color', 'attr-size', 'attr-fabric', 'attr-fit'] },
  { id: 'cat-mens-shirts', name: "Men's Shirts", slug: 'mens-shirts', parentId: 'cat-men', status: 'active', sortOrder: 2, attributeIds: ['attr-color', 'attr-size', 'attr-fabric', 'attr-fit'] },
  { id: 'cat-mens-hoodies', name: "Men's Hoodies", slug: 'mens-hoodies', parentId: 'cat-men', status: 'active', sortOrder: 3, attributeIds: ['attr-color', 'attr-size', 'attr-fabric'] },
  { id: 'cat-mens-jeans', name: "Men's Jeans", slug: 'mens-jeans', parentId: 'cat-men', status: 'active', sortOrder: 4, attributeIds: ['attr-color', 'attr-size', 'attr-fit'] },
  { id: 'cat-mens-joggers', name: "Men's Joggers", slug: 'mens-joggers', parentId: 'cat-men', status: 'active', sortOrder: 5, attributeIds: ['attr-color', 'attr-size'] },
  { id: 'cat-womens-tops', name: "Women's Tops", slug: 'womens-tops', parentId: 'cat-women', status: 'active', sortOrder: 1, attributeIds: ['attr-color', 'attr-size', 'attr-fabric'] },
  { id: 'cat-womens-kurti', name: 'Kurti', slug: 'womens-kurti', parentId: 'cat-women', status: 'active', sortOrder: 2, attributeIds: ['attr-color', 'attr-size', 'attr-fabric'] },
  { id: 'cat-womens-dresses', name: 'Dresses', slug: 'womens-dresses', parentId: 'cat-women', status: 'active', sortOrder: 3, attributeIds: ['attr-color', 'attr-size', 'attr-fabric'] },
  { id: 'cat-womens-jeans', name: "Women's Jeans", slug: 'womens-jeans', parentId: 'cat-women', status: 'active', sortOrder: 4, attributeIds: ['attr-color', 'attr-size', 'attr-fit'] },
  { id: 'cat-bags', name: 'Bags', slug: 'bags', parentId: 'cat-accessories', status: 'active', sortOrder: 1, attributeIds: ['attr-color'] },
  { id: 'cat-belts', name: 'Belts', slug: 'belts', parentId: 'cat-accessories', status: 'active', sortOrder: 2, attributeIds: ['attr-color'] },
];
